Register-PSFTeppScriptblock -Name 'PkiExtension.CertificateProperties' -ScriptBlock {
	'Binary Certificate'
	'Binary Request'
	'Certificate Effective Date'
	'Certificate Expiration Date'
	'Certificate Hash'
	'Certificate Template'
	'Effective Revocation Date'
	'Issued Common Name'
	'Issued Request ID'
	'Request Common Name'
	'Request Disposition Message'
	'Request ID'
	'Request Status Code'
	'Request Submission Date'
	'Requester Name'
	'Revocation Date'
	'Revocation Reason'
} -Global